### PR TITLE
Enhancements to Whisper ASR Integration

### PR DESCRIPTION
**Pull request by bscholer**
This PR introduces enhancements to the Whisper ASR service integration, adding support for timestamps, word-level timestamps, and various other configurable options. These additions aim to increase the versatility of the service without affecting existing functionalities or tests.

## Features

- **Timestamp Support**: Enables the inclusion of timestamps in Whisper ASR transcriptions, providing more detailed information about the timing of spoken words.
- **Translation Support**: Facilitates translation capabilities within Whisper ASR, allowing for more diverse applications.
- **Extended Configuration Options**: Introduces additional settings for Whisper ASR to customize its behavior further.

## New Configuration Options:

- **`encode`**: Enabled by default. Testing has shown that this setting does not impact the quality of transcriptions.
- **`initialPrompt`**: Allows users to specify spellings for difficult names or words, or to request transcriptions in a specific style. It's advisable to consult the [Whisper Prompting Guide](https://cookbook.openai.com/examples/whisper_prompting_guide) to leverage this feature effectively. This capability was a key motivation for the current PR.
- **`vadFilter`**: Targets silence detection. Our tests indicate minimal impact on transcription quality from this feature, aside from a slight reduction in processing speed. It is disabled by default, consistent with Whisper ASR's default behavior.
- **`wordTimestamps`**: Offers word-level timestamp information instead of just segment-level, providing finer detail on the timing of each word.

## Implementation Details:

The primary focus of this update was to refine the handling of Whisper ASR responses, particularly to utilize JSON responses which contain more detailed information, such as timestamps, compared to the default text responses.

- **Type Definitions**: Added TypeScript definitions for the Whisper ASR JSON response (`src/types/whisper-asr.ts`).
- **Response Processing**: Implemented a utility function (`src/utils.ts:preprocessWhisperASRResponse`) to parse the raw JSON response from Whisper ASR and convert it into a more structured and usable format.
- **Timestamps and Translation**: Enhanced the transcription logic (`src/transcribe.ts`) to support both timestamps and word-level timestamps, alongside the newly introduced translation capability.
- **Configuration Settings**: Updated the settings module (`src/settings.ts`) to include the new options and ensure they integrate seamlessly with the existing configuration structure.
- **UI Adjustments**: Modified the settings UI to conditionally display Timestamp Format and Word Timestamps options based on the status of the Timestamps setting. A note for future development includes refactoring the repetitive class checking logic into a separate utility function for better maintainability.

### Additional Notes:

The enhancements outlined in this PR are designed to bolster the functionality of Whisper ASR within our application, providing users with greater flexibility and control over their transcription and translation tasks.

### CODE REVIEW

**Comment by djmango** [comment]
Was this covered by the other PR?

**Comment by bscholer** [comment]
> Was this covered by the other PR?

This wasn't covered, but I realized that the reason the ASR wasn't returning timestamps was because the default `output` was `txt`, which only sent back the response. Currently switching things over to request `json` responses, which provide much more info. Will update this PR once I get this done.

**Comment by bscholer** [comment]
@djmango This PR has pretty significant changes to the Whisper ASR integration. Please see the primary PR comment at the top of the thread, it is updated with a detailed summary of new features and work done.

Thanks for making this plugin to begin with!!

**Comment by djmango** [comment]
LGTM! thanks for the contributions, they're much appreciated!

**Pull request merged**
