### PR TITLE
Single line responses

### PR DESCRIPTION
**Pull request by amunrarara**
Experimental, untested, but will possibly remedy the issue described in Issue #40

### CODE REVIEW

**Comment by amunrarara** [comment]
@djmango Please review

**Comment by djmango** [comment]
I've run a workflow to package the plugin with this code. However, this behavior change should be a setting, not a change in default. Please update accordingly and I'm happy to merge!

**Comment by amunrarara** [comment]
Awesome, thanks for your reply! Can you explain your response a bit? I didn't quite understand what you meant.

**Comment by djmango** [comment]
You're welcome to make the change with your own copy of the plugin, but the default behavior (what people have come to expect from the plugin) should not be changed. Happy to merge this into the distributed plugin if you made it a setting though.

**Comment by amunrarara** [comment]
@djmango Excellent, that makes sense. I've made the changes, let me know if they're good-to-go! 

FYI I haven't tested, because I don't have the local workflow set up yet for testing custom Obsidian plugins. Will set up the workflow for myself in the future.

**Comment by amunrarara** [comment]
@djmango Fixing error, one moment

**Comment by djmango** [comment]
That's the purpose of the workflow. It auto packages the application for you to test. It seems to have failed

https://github.com/djmango/obsidian-transcription/actions/runs/7722208435/job/21050070060?pr=41

The commands to test it yourself are also in the YAML

**Comment by amunrarara** [comment]
@djmango K, I've pushed the fix, let's see if the workflow is happy with it

**Comment by djmango** [comment]
LGTM

**Comment by amunrarara** [comment]
Woot woot! +1 and thank you!

**Comment by amunrarara** [comment]
@djmango How long until the changes are live in the Obsidian Community Plugin update menu?

**Comment by djmango** [comment]
Should be up

**Pull request merged**
